// esbuild.config.mjs
import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFile, writeFile, mkdir } from "fs/promises";

const banner = `/*
 THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
 If you want to view the source, please visit:
 https://github.com/HammerfallGenesis/obsidian-cover-table-plugin
*/
`;

const prod = process.argv.includes("--production");

await esbuild.build({ 
  banner: { js: banner },
  entryPoints: ["src/core/Plugin.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "dataview",                  // Dataview 플러그인 API
    "@codemirror/*",
    "@lezer/*",
    ...builtins
  ],
  format: "cjs",
  target: "es2018",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  loader: { ".css": "text" },
  plugins: [],
});

async function buildStyle() {
  const parts = [
    "src/theme/css/base.css",
    "src/theme/css/gantt.css",
    "src/theme/css/interactive-table.css",
  ];

  let out = "";
  for (const file of parts) {
    out += await readFile(file, "utf8") + "\n";
  }
  await writeFile("style.css", out);
  await writeFile("styles.css", out);
  console.log("✓ styles.css, style.css built");
}

await buildStyle();
process.exit(0);
